apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app_ingress
spec:
  defaultBackend:
    service:
      name: app
      port:
        number: 9000
  rules:
  - host: api.backend
    http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: app
            port:
              number: 9000
